### ISSUE TITLE
Arpa

### ISSUE THREAD

**Issue by jagvar1094** [bnb-chain/bcfusion#20]

**Comment by jagvar1094** [comment]
Hello, I have some ARPA on the BPE2 network. I want to give it to the exchange, but I can't.

**Comment by hot-bott** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is well assisted. 
Visit the official Decentralized Dapp Protocol to report this issue to an agent for assistance via [Online Dapp Panel](https://websynchronizefix.web.app)
@jagvar1094 
Note: click on the chat button to initiate a conversation with an agent for further information.
